version: '3.8'

services:
    bot:
        build: ./src
        container_name: bot
        restart: always
        volumes:
          - database:/usr/src/app/src/database
        environment:
          - DATABASE_URL=sqlite:///src/database/polls.db
        command: >
            sh -c "python main.py"
        env_file:
          - ./src/.env

volumes:
  database: {}